version: '3.3'

services:
  mainscore:
    build:
      context: .
      dockerfile: Dockerfile
    image: mor12324/scoreapp:latest
    volumes:
      - /vagrant/Docker:/app
    ports:
      - "8777:5000"
    restart: always
